### ISSUE TITLE
where to download the dataset?

### ISSUE THREAD

**Issue by zeroyang0809** [destiny301/PMFL#2]
hello i want to ask a question
where to download the dataset?
thank you

**Comment by destiny301** [comment]
Hi,

Here are the references for you,
MIMIC-CXR Database: https://physionet.org/content/mimic-cxr/2.0.0/
eICU: https://eicu-crd.mit.edu/gettingstarted/access/

Hope it helps. 😊

**Comment by zeroyang0809** [comment]
thanks you for your help 

but when i run the main.py
it shows FileNotFoundError: [Errno 2] No such file or directory: '../datasets\\mimic\\mimic-cxr-2.0.0-chexpert.csv'

i could not find the datasets\mimic\mimic-cxr-2.0.0-chexpert.csv at  https://physionet.org/content/mimic-cxr/2.0.0/ this URL 

Could you offer more specific help? thanks


![Screenshot 2024-02-21 232438](https://github.com/destiny301/PMFL/assets/116786638/ab23ae73-0b35-4690-801d-96566174fb13)

**Comment by destiny301** [comment]
I think you can find it on this page,
https://physionet.org/content/mimic-cxr-jpg/2.0.0/

**Comment by zeroyang0809** [comment]
Thanks for your excellent work. I want to confirm the details.

 In the experiment, there are 8 kinds of diseases .Each client corresponds to one disease.

MAML is done on each client separately(during client training, only one disease on each client will be used for training). After each client sum up the total training task loss, the loss will be return to server for model update

Is that right?

Thank you so much.

**Comment by destiny301** [comment]
yes, you understand correctly.
